// Demo mode: Whitehouse Property Group has no real SevenRooms connection.
// This module intentionally has no live client -- all SevenRooms-branded
// data in this dashboard is generated by lib/mock/reservations.ts instead.
// Kept as an empty stub so any stray import fails loudly at build time
// rather than silently calling a real external API with no credentials.
export {};
